apiVersion: apps/v1
kind: Deployment
metadata:
  name: fliperama
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fliperama
  template:
    metadata:
      labels:
        app: fliperama
    spec:
      containers:
      - name: fliperama
        image: magicalyak/docker-games:marioluigi
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fliperama-service
spec:
  selector:
    app: fliperama
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
  type: LoadBalancer
  externalTrafficPolicy: Cluster
